sylius_resource:
    resources:
        ipanema_sylius_seo_page_plugin.seopage:
            driver: doctrine/orm
            classes:
                model: Ipanema\SyliusSeoPagePlugin\Entity\SeoPage
                interface: Ipanema\SyliusSeoPagePlugin\Entity\SeoPageInterface
                repository: Ipanema\SyliusSeoPagePlugin\Repository\SeoPageRepository
                form: Ipanema\SyliusSeoPagePlugin\Form\Type\SeoPageType
            translation:
                classes:
                    model: Ipanema\SyliusSeoPagePlugin\Entity\SeoPageTranslation
                    interface: Ipanema\SyliusSeoPagePlugin\Entity\SeoPageTranslationInterface
